CREATE TABLE QLKB
CREATE TABLE BENHNHAN (
    MABN CHAR(5) PRIMARY KEY,
    HOTENBN NVARCHAR(50),
    NGAYSINH SMALLDATETIME,
    CCCD NVARCHAR(12),
    SOBHYT NVARCHAR(15),
    BHYTCHITRA FLOAT,
    DIACHI NVARCHAR(100)
)
CREATE TABLE BACSI (
    MABS CHAR(5) PRIMARY KEY,
    HOTENBS NVARCHAR(50),
    NGAYBDLV SMALLDATETIME,
    CHUYENKHOA NVARCHAR(50)
)
CREATE TABLE KHAMBENH (
    MAKB CHAR(5) PRIMARY KEY,
    MABN CHAR(5),
    MABS CHAR(5),
    NGAYKHAM SMALLDATETIME,
    TRIEUCHUNG NVARCHAR(255),
    KETLUAN NVARCHAR(255),
    TAIKHAM INT,
    CONSTRAINT FK_KHAMBENH_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    CONSTRAINT FK_KHAMBENH_BACSI FOREIGN KEY (MABS) REFERENCES BACSI(MABS),
)
CREATE TABLE THUOC (
    MATHUOC CHAR(5),
    TENTHUOC NVARCHAR(50),
    LOAITHUOC NVARCHAR(20),
    DONGIA MONEY
)
CREATE TABLE DONTHUOC (
    MADT CHAR(5),
    MAKB CHAR(5),
    TRIGIADT MONEY,
    BHYTCHITRA FLOAT,
    NGAYCAPTHUOC SMALLDATETIME,
    TONGTIENTT MONEY,
    TINHTRANGDT NVARCHAR(30),
    CONSTRAINT FK_DONTHUOC_KHAMBENH FOREIGN KEY (MAKB) KHAMBENH(MAKB)
)
CREATE TABLE CHITIETDT (
    MADT CHAR(5),
    MATHUOC CHAR(5),
    SOLUONG INT,
    THANHTIEN MONEY,
    CONSTRAINT PK_CTDT PRIMARY KEY (MADT, MATHUOC),
    CONSTRAINT FK_CTDT_DONTHUOC FOREIGN KEY (MADT) DONTHUOC(MADT),
    CONSTRAINT FK_CTDT_THUOC FOREIGN KEY (MATHUOC) THUOC(MATHUOC)
)
---2.1
ALTER TABLE BENHNHAN 
ADD CONSTRAINT CHK_BHYTCHITRA CHECK (BHYTCHITRA >= 0 AND BHYTCHITRA <= 0.7)
---2.2 
ALTER TABLE DONTHUOC
ADD CONSTRAINT CHK_TINHTRANGTT CHECK (TINHTRANGDT IN ('CHUA THANH TOAN', 'DA THANH TOAN'))
---2.3
CREATE TRIGGER INSERT_CTDT
ON CHITIETDT 
AFTER INSERT 
AS 
    IF EXISTS (SELECT * 
            FROM DONTHUOC DT 
            WHERE DT.TRIGIADT != (SELECT SUM(THANHTIEN)
                                FROM INSERTED I 
                                WHERE I.MADT = DT.MADT))
BEGIN 
    ROLLBACK TRANSACTION
    PRINT 'TRI GIA DON THUOC PHAI BANG TONG THANH TIEN CUA CAC CHI TIET THUOC DON DO'
END
---3.1
SELECT BS.MABS, HOTENBS, BN.MABN, HOTENBN
FROM BACSI BS 
JOIN KHAMBENH KB ON BS.MABS = KB.MAKB
JOIN BENHNHAN BN ON KB.MABN = BN.MABN
WHERE CHUYENKHOA = 'TAI MUI HONG' AND YEAR(NGAYKHAM) = 2024
---3.2
SELECT BN.MABN, HOTENBN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON BN.MABN = KB.BN
JOIN DONTHUOC DT ON KB.MAKB = KB.MAKB
WHERE YEAR(NGAYKHAM) = 2024
EXCEPT
SELECT BN.MABN, HOTENBN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON BN.MABN = KB.BN
JOIN DONTHUOC DT ON KB.MAKB = KB.MAKB
WHERE YEAR(NGAYKHAM) = 2024 AND TONGTIENTT >= 100000 TINHTRANGDT = 'DA THANH TOAN'
---3.3 
SELECT DT.MADT, MAKB
FROM DONTHUOC DT
WHERE YEAR (NGAYCAPTHUOC) = 2024
AND NOT EXISTS (SELECT * 
                FROM THUOC TH
                WHERE LOAITHUOC = 'THUOC DI UNG'
                AND NOT EXISTS (SELECT *
                                CHITIETDT CTDT 
                                WHERE CTDT.MADT = DT.MADT AMD CTDT.MATHUOC = CTDT.MATHUOC))
---3.4
SELECT BN.MABN, HOTENBN, COUNT(MADT) AS SOLUONGDT
FROM BENHNHAN BN
LEFT JOIN KHAMBENH KB ON BN.MABN = KB.MABN
LEFT JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB
WHERE YEAR(NGAYCAPTHUOC) = 2024 AND SOBHYT IS NULL AND TINHTRANGDT = 'DA THANH TOAN'
GROUP BY BN.MABN, HOTENBN
---3.5 Z
SELECT BN.MABN, HOTENBN
FROM BENHNHAN BN 
JOIN KHAMBENH KB ON BN.MABN = KB.MABN
JOIN DONTHUOC DT ON KB.KB = DT.MADT
WHERE YEAR(NGAYCAPTHUOC) = 2024 AND TINHTRANGDT = 'DA THANH TOAN'
AND BN.MABN IN (SELECT TOP 1 WITH TIES BN.MABN
                FROM BENHNHAN BN
                JOIN KHAMBENH KB ON BN.MABN = KB.MAKB
                GROUP BY BN.MABN
                ORDER BY COUNT(MAKB) ASC)
GROUP BY BN.MABN, HOTENBN
HAVING SUM(TONGTIENTT) < 100000