CREATE DATABASE QLPT202
CREATE TABLE PHONGTRO (
	MAPT CHAR(5) PRIMARY KEY,
	TENPT NVARCHAR(50),
	DIENTICH FLOAT,
	LOAIPT NVARCHAR (15),
	GIAPT MONEY,
	TRINHTRANGPT NVARCHAR(20)
)
CREATE TABLE CUDAN (
	MACD CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR (50),
	CCCD NVARCHAR (12),
	DIACHI NVARCHAR(100),
	SODT VARCHAR(15),
	TRANGTHAICD NVARCHAR(15)
)
CREATE TABLE HOPDONG (
	MAHD CHAR(5) PRIMARY KEY,
	MACD CHAR(5),
	MAPT CHAR(5),
	NGAYKY SMALLDATETIME,
	NGAYHETHAN SMALLDATETIME,
	TRANGTHAIHD NVARCHAR(20),
	CONSTRAINT FK_HOPDONG_CUDAN FOREIGN KEY (MACD) REFERENCES CUDAN(MACD)
	CONSTRAINT FK_HOPDONG_PHONGTRO FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)
)
CREATE TABLE DICHVU (
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(50),
	DONGIA MONEY
)
CREATE TABLE PHIEUTINHTIEN (
	MAPTT CHAR(5) PRIMARY KEY,
	MAHD CHAR(5),
	SOTIENDICHVU MONEY,
	SOTIENTHUEPTT MONEY,
	TONGTIENTT MONEY,
	NGAYTINHTIEN SMALLDATETIME,
	TINHTRANGTT NVARCHAR(20),
	PHUONGTHUCTT NVARCHAR(20),
	CONSTRAINT FK_PHIEUTT_MAHD FOREIGN KEY (MAHD) REFERENCES HOPDONG(MAHD)
)
CREATE TABLE CHITIETTTDV (
	MAPTT CHAR(5),
	MADV CHAR(5),
	CHISODV FLOAT,
	THANHTIEN MONEY,
	CONSTRAINT PK_CTDV PRIMARY KEY (MAPTT, MADV),
	CONSTRAINT FK_CTDV_PHIEUTT FOREIGN KEY (MAPTT) REFERENCES PHIEUTINHTIEN(MAPTT)
	CONSTRAINT FK_CTDV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
)
---2.1
ALTER TABLE HOPDONG 
ADD CONSTRAINT CHK_NGAYKY CHECK (NGAYKY <= NGAYHETHAN)
---2.2
ALTER TABLE PHONGTRO
ADD CONSTRAINT CHK_TRINHTRANGPT CHECK (TRINHTRANGPT IN ('TRONG', 'DA CHO THUE'))
---2.3
CREATE TRIGGER INSERT_CTDV
ON CHITIETTTDV
AFTER DELETE 
AS
	IF EXISTS (SELECT *
			FROM PHIEUTINHTIEN PTT
			WHERE SOTIENDICHVU <> (SELECT SUM(THANHTIEN)
								FROM DELETE D
								WHERE D.MAPTT = PTT.MAPTT))
BEGIN 
	ROLLBACK TRANSACTION
	PRINT 'SO TIEN DICH VU DA SU DUNG PHAI BANG TO THANH TIEN CAC CHI TIET DICH VU'
END
---3.1
SELECT PT.MAPT, TENPT, PTT.MAPTT, TONGTIENTT
FROM PHONGTRO PT 
JOIN HOPDONG HD ON PT.MAPT = HD.MAHD
JOIN PHIEUTINHTIEN PTT ON HD.MAHD = PTT.MAHD
WHERE TINHTRANGTT = 'DA CHO THUE' AND YEAR(NGAYTINHTIEN) = 2024
---3.2
SELECT CD.MACD, HOTEN
FROM CUDAN CD 
JOIN HOPDONG HD ON CD.MACD = HD.MACD
JOIN PHONGTRO PT ON HD.MAPT = PT.MAPT
WHERE DIENTICH > 20 AND LOAIPT = 'KIOT' AND YEAR(NGAYKY) = 2024
INTERSECT 
SELECT CD.MACD, HOTEN
FROM CUDAN CD 
JOIN HOPDONG HD ON CD.MACD = HD.MACD
JOIN PHONGTRO PT ON HD.MAPT = PT.MAPT
WHERE DIENTICH > 20 AND LOAIPT = 'CO GAC XEP' AND YEAR(NGAYKY) = 2024
---3.3
---C1
SELECT MAPTT, MAHD
FROM PHIEUTINHTIEN PTT
WHERE TONGTIENTT > 2000000 AND PHUONGTHUCTT = 'TIEN MAT'
AND NOT EXISTS (SELECT * 
				FROM DICHVU 
				WHERE DONGIA <= 50000
				AND NOT EXISTS (SELECT * 
								FROM CHITIETTTDV CTDV
								WHERE CTDV.MAPTT = PTT.MAPTT AND CTDV.MADV = DV.MADV))
---C2
SELECT PTT.MAPTT, PTT.MAHD
FROM PHIEUTINHTIEN PTT
JOIN CHITIETTTDV CTDV ON PTT.MAPTT = CTDV.MAPTT
JOIN DICHVU DV ON CTDV.MADV = DV.MADV
WHERE TONGTIENTT > 2000000 AND PHUONGTHUCTT = 'TIEN MAT' AND DONGIA < 50000
GROUP BY PTT.MAPTT, PTT.MAHD
HAVING COUNT(DISTINCT DV.MADV) = (SELECT COUNT(*)
								FROM DICHVU
								WHERE DONGIA < 50000)
---3.4
SELECT CD.MACD, HOTEN, COUNT(MAHD) AS SOLUONGHD
FROM CUDAN CD
LEFT JOIN HOPDONG HD ON CD.MACD = HD.MACD
WHERE YEAR(NGAYHETHAN) = 2024 AND TRANGTHAIHD = 'DA HET HAN'
GROUP BY CD.MACD, HOTEN
---3.5
SELECT PTT.MAHD
FROM PHIEUTINHTIEN PTT
WHERE PTT.MAHD IN (SELECT TOP 1 WITH TIES MAHD
					FROM PHIEUTINHTIEN PTT
					JOIN CHITIETTTDV CTDV ON PTT.MAPTT = DV.MAPTT
					JOIN DICHVU DV ON DV.MADV = CTDV.MADV
					WHERE TENDV = 'DIEN'
					GROUP BY MAHD
					ORDER BY SUM(CHISODV) ASC)
GROUP BY PTT.MAHD
HAVING COUNT(PTT.MAPTT) >= 2
